#!/bin/bash


# list of variable for tecplot-macro
varnamel="'\"x\" \"y\" \"phase'" 

# length of x and y axis
Lx=1
Ly=1

# length of main x and y ticks
tickslx=0
ticksly=0

# length of minor x and y ticks
mtickslx=0
mticksly=0


# prepare macro file to tecplot
# args: $1-input $2-zeros $3-fileNumber
# input file name is constructed as $1$2$3 

function make_mcr {
echo "#!MC 1200" > $1.temp.mcr
echo "# Created by Tecplot 360 build 12.2.0.9077" >> $1.temp.mcr
echo "\$!READDATASET  '\"$1\" '" >> $1.temp.mcr
echo "  READDATAOPTION = NEW" >> $1.temp.mcr
echo "  RESETSTYLE = YES" >> $1.temp.mcr
echo "  INCLUDETEXT = NO" >> $1.temp.mcr
echo "  INCLUDEGEOM = NO" >> v.temp.mcr
echo "  INCLUDECUSTOMLABELS = NO" >> $1.temp.mcr
echo "  VARLOADMODE = BYNAME" >> $1.temp.mcr
echo "  ASSIGNSTRANDIDS = YES" >> $1.temp.mcr
echo "  INITIALPLOTTYPE = CARTESIAN2D" >> $1.temp.mcr
echo "  VARNAMELIST = $varnamel" >> $1.temp.mcr
echo "\$!GLOBALCONTOUR 1  VAR = 3" >> $1.temp.mcr
echo "\$!CONTOURLEVELS RESETTONICE" >> $1.temp.mcr
echo "  CONTOURGROUP = 1" >> $1.temp.mcr
echo "  APPROXNUMVALUES = 15" >> $1.temp.mcr
echo "\$!FIELDLAYERS SHOWCONTOUR = YES" >> $1.temp.mcr
echo "\$!REDRAWALL " >> $1.temp.mcr
echo "\$!TWODAXIS XDETAIL{SHOWAXIS = NO}" >> $1.temp.mcr
echo "\$!REDRAWALL " >> $1.temp.mcr
echo "\$!TWODAXIS YDETAIL{SHOWAXIS = NO}" >> $1.temp.mcr
echo "\$!FIELDMAP [1]  CONTOUR{CONTOURTYPE = PRIMARYVALUE}">> $1.temp.mcr
echo "\$!GLOBALCOLORMAP 1  CONTOURCOLORMAP = USERDEF" >> $1.temp.mcr
echo "\$!COLORMAPCONTROL 1 COPYSTANDARD" >> $1.temp.mcr
echo "  CONTOURCOLORMAP = GRAYSCALE" >> $1.temp.mcr
echo "\$!COLORMAPCONTROL 1 REDISTRIBUTECONTROLPOINTS" >> $1.temp.mcr
echo "\$!REDRAWALL " >> $1.temp.mcr
echo "\$!EXPORTSETUP EXPORTFORMAT = JPEG" >> $1.temp.mcr
echo "\$!EXPORTSETUP IMAGEWIDTH = 791" >> $1.temp.mcr
echo "\$!EXPORTSETUP  QUALITY = 100" >> $1.temp.mcr
echo "\$!EXPORTSETUP EXPORTFNAME = '$1.jpg'" >> $1.temp.mcr
echo "\$!EXPORT " >> $1.temp.mcr
echo "  EXPORTREGION = CURRENTFRAME" >> $1.temp.mcr
echo "\$!QUIT" >> $1.temp.mcr
}

for i in phase*.plt; do
	FILENAME=`basename $i`
	make_mcr $FILENAME;
	#execute tecplot
    /opt/tecplot360/bin/tec360 -b $FILENAME.temp.mcr
	convert -crop 550x550+100+80 $FILENAME.jpg $FILENAME.jpg
done

