all: ConstructHistogram1 ConstructWHistogram

ConstructHistogram1: ConstructHistogram1.cpp
	g++ -o ConstructHistogram1 ConstructHistogram1.cpp

ConstructWHistogram: ConstructWHistogram.cpp
	g++ -o ConstructWHistogram ConstructWHistogram.cpp

clean:
	rm -rf *.o ConstructHistogram1 ConstructWHistogram
